# Generated by Django 5.0.7 on 2024-09-06 17:43

import course.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_image',
            field=models.ImageField(default='course/images/default_course.png', upload_to=course.utils.get_upload_to),
        ),
    ]
