# Generated by Django 5.0.7 on 2024-08-31 00:37

import accounts.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('profile_picture', models.ImageField(blank=True, upload_to=accounts.utils.get_upload_to)),
                ('phone_number', models.CharField(max_length=12)),
                ('role', models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher')], max_length=10)),
                ('created_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
